---
 - name: Install postgresql dependencies (yum)
   yum: state=installed name={{ item }}
   with_items:
    - postgresql-server
    - postgresql-devel
    - python-psycopg2
   when: ansible_os_family == "RedHat"

 - name: Install postgresql dependencies (apt)
   apt: state=installed name={{ item }}
   with_items:
    - postgresql
    - libpq-dev
    - python-psycopg2
   when: ansible_os_family == "Debian"

 - name: Install postgresql dependencies (portage)
   portage: state=installed name={{ item }}
   with_items:
    - dev-db/postgresql
    - dev-python/psycopg
   when: ansible_os_family == "Gentoo"

 #@@@ ignore for testing
 - name: Init postgresql server
   command: postgresql-setup initdb
   when: ansible_os_family == "RedHat"
   ignore_errors: True

 - name: Enable postgresql server
   service: name=postgresql state=started enabled=yes

 - name: Create reviewboard DB
   postgresql_db:
     name={{ sql_database_name }} state=present
   become: yes
   become_user: postgres

 - name: Create reviewboard DB user
   postgresql_user:
     db={{ sql_database_name}}
     name={{ sql_username}}
     password={{ sql_password }}
     priv=ALL
     state=present
   become: yes
   become_user: postgres
