---
 - name: Open http port (firewalld)
   firewalld: port={{ http_port }}/tcp permanent=true state=enabled
   notify:
   - Firewalld reload
   when: firewall == "firewalld"

 - name: Open http port (ufw)
   ufw: rule=allow port={{ http_port }} proto=tcp
   when: firewall == "ufw"

 - name: Open http port (iptables)
   iptables: chain=INPUT destination_port={{ http_port }} protocol=tcp jump=ACCEPT
   when: firewall == "iptables"

